### CREATE volunteer
POST http://localhost:3000/volunteer
Content-Type: application/json

{
  "username": "Mark",
  "email": "mark@example.com",
  "location": "Paris"
}

### READ all volunteers
GET http://localhost:3000/volunteers

# ### READ volunteers by location
# GET http://localhost:3000/volunteer/location/Paris

# ### UPDATE volunteer
# PUT http://localhost:3000/volunteer/1
# Content-Type: application/json

# {
#   "name": "Alice Updated",
#   "email": "alice.updated@example.com",
#   "location": "Lyon"
# }

# ### DELETE volunteer
# DELETE http://localhost:3000/volunteer/1
